"""Initial migration with named constraints

Revision ID: 42f5a2078544
Revises: 
Create Date: 2024-08-03 00:25:39.482969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f5a2078544'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activities', schema=None) as batch_op:
        batch_op.alter_column('Date',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['Email'])

    with op.batch_alter_table('Interactions', schema=None) as batch_op:
        batch_op.alter_column('InteractionID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('CustomerID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('InteractionDate',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('InteractionType',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('Orders', schema=None) as batch_op:
        batch_op.alter_column('OrderID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('CustomerID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('OrderDate',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('Status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('TotalAmount',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)

    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.alter_column('ProductID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('ProductName',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('ProductDescription',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('Price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['Email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.alter_column('Price',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('ProductDescription',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('ProductName',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('ProductID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('Orders', schema=None) as batch_op:
        batch_op.alter_column('TotalAmount',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('Status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('OrderDate',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
        batch_op.alter_column('CustomerID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('OrderID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('Interactions', schema=None) as batch_op:
        batch_op.alter_column('InteractionType',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('InteractionDate',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
        batch_op.alter_column('CustomerID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('InteractionID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('Activities', schema=None) as batch_op:
        batch_op.alter_column('Date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
